In [1]:
import torch

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [3]:
print(x.data)
x = x * 2

tensor([[1., 1.],
        [1., 1.]])


In [4]:
print(x.grad_fn)

In [5]:
y = x+2
print(y)

tensor([[4., 4.],
        [4., 4.]], grad_fn=<AddBackward>)


In [6]:
print(y.grad_fn)

In [7]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[48., 48.],
        [48., 48.]], grad_fn=<MulBackward>) tensor(48., grad_fn=<MeanBackward1>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
#print(a.grad_fn)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [9]:
out.backward()
print(out.grad)


None


In [10]:
x = torch.ones(2, 2, requires_grad=True)
y = x + 2
y.backward(torch.ones(2, 2), retain_graph=True)
print(x.grad)


tensor([[1., 1.],
        [1., 1.]])


In [11]:
z = y * y
print(z)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<ThMulBackward>)


In [12]:
gradient = torch.randn(2, 2)
y.backward(gradient)
print(x.grad)

tensor([[1.3935, 1.0080],
        [2.1640, 1.6793]])
