In [1]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(3, 4)
print(x)

tensor([[                                      0.0001,
                                               0.0000,
           -957749325641034387942205669460934656.0000,
                                               0.0000],
        [                                         nan,
                                               0.0000,
           -305351042757675784117825119759368192.0000,
                                               0.0000],
        [  -957750593291634616171607166164140032.0000,
                                               0.0000,
         -98271357455952098257928872462942994432.0000,
                                               0.0000]])


In [6]:
x = torch.rand(2, 2)
print(x)

tensor([[0.6676, 0.6469],
        [0.1860, 0.8297]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [20]:
x = torch.randn_like(x, dtype=torch.float)
print(x)


tensor([[ 2.1171,  0.6643, -0.4787],
        [-1.6668,  1.7588, -0.1875],
        [-1.5271, -0.1709, -0.6349],
        [ 0.1998,  0.3326, -0.1276],
        [ 0.1285, -0.3302,  0.2120]])


In [21]:
print(x.size())

torch.Size([5, 3])


In [22]:
y = torch.rand(5, 3)
print(y)
print(torch.add(y, x))

tensor([[0.9490, 0.7794, 0.3787],
        [0.4194, 0.8726, 0.7976],
        [0.6275, 0.1057, 0.7675],
        [0.3233, 0.9937, 0.3955],
        [0.1908, 0.7485, 0.8739]])
tensor([[ 3.0662,  1.4437, -0.1001],
        [-1.2474,  2.6313,  0.6102],
        [-0.8996, -0.0652,  0.1326],
        [ 0.5231,  1.3263,  0.2679],
        [ 0.3193,  0.4183,  1.0860]])


In [23]:
result = torch.empty(5, 3)
torch.add(y, x, out=result)
print(result)

tensor([[ 3.0662,  1.4437, -0.1001],
        [-1.2474,  2.6313,  0.6102],
        [-0.8996, -0.0652,  0.1326],
        [ 0.5231,  1.3263,  0.2679],
        [ 0.3193,  0.4183,  1.0860]])


In [24]:
y.add_(x)

tensor([[ 3.0662,  1.4437, -0.1001],
        [-1.2474,  2.6313,  0.6102],
        [-0.8996, -0.0652,  0.1326],
        [ 0.5231,  1.3263,  0.2679],
        [ 0.3193,  0.4183,  1.0860]])

In [25]:
print(x[:, 1])

tensor([ 0.6643,  1.7588, -0.1709,  0.3326, -0.3302])


In [28]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size()), y.size(), z.size()

torch.Size([4, 4])


(None, torch.Size([16]), torch.Size([2, 8]))

In [29]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6103])
-0.6102981567382812


In [30]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [35]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

tensor([0.3897], device='cuda:0')
tensor([0.3897], dtype=torch.float64)
